id: D927DDD64
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-07T09:22:53+00:00'
last_modified: '2022-05-30T06:39:16.072319+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    940e:
      image_group_id: I1PD95961
      title: བཀྲ་ཤིས་ཀྱི་ཚིགས་སུ་བཅད་པ།
      total_pages: 1880
      order: 116
      base_file: 940e.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
