id: PEB7957F9
initial_creation_type: ocr
source_metadata:
  volumes:
    c5fc2869249d4a99ab24c7ad90d8d394:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: བཀྲ་ཤིས་ཀྱི་ཚིགས་སུ་བཅད་པ།
      total_pages: 1880
      volume_number: 116
